# Generated by Django 2.0.1 on 2018-03-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimedata',
            fields=[
                ('id', models.PositiveIntegerField(default=0, editable=False, primary_key=True, serialize=False)),
                ('bay_id', models.PositiveIntegerField(default=0)),
                ('lat', models.CharField(default='default', max_length=50)),
                ('lon', models.CharField(default='default', max_length=50)),
                ('st_market_id', models.CharField(default='default', max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('ParkingDate', models.DateTimeField()),
            ],
        ),
    ]
