# Generated by Django 2.0.1 on 2018-04-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkdata', '0002_auto_20180328_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockquery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.IntegerField(db_column='DeviceId')),
                ('streemarker', models.CharField(db_column='StreeMarker', max_length=40)),
                ('blockid', models.IntegerField(db_column='BlockId')),
            ],
            options={
                'db_table': 'blockQuery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Finetreepredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockid', models.IntegerField(db_column='BlockId')),
                ('period_h', models.IntegerField(db_column='Period_h')),
                ('period_m', models.IntegerField(db_column='Period_m')),
                ('volume', models.FloatField(db_column='Volume')),
                ('predicted', models.FloatField(db_column='Predicted')),
            ],
            options={
                'db_table': 'FineTreePredict',
                'managed': False,
            },
        ),
    ]
