# Generated by Django 2.0.1 on 2018-04-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkdata', '0003_blockquery_finetreepredict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekly1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockid', models.IntegerField(db_column='BlockId')),
                ('period_h', models.IntegerField(db_column='Period_h')),
                ('period_m', models.IntegerField(db_column='Period_m')),
                ('volume', models.FloatField(db_column='Volume')),
                ('weekday', models.IntegerField(db_column='Weekday')),
                ('predicted', models.FloatField(db_column='Predicted')),
            ],
            options={
                'db_table': 'Weekly1',
                'managed': False,
            },
        ),
    ]
