# Generated by Django 2.0.1 on 2018-05-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkdata', '0005_weekly2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lastfridata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bay_id', models.IntegerField()),
                ('occupiedrate', models.FloatField(db_column='occupiedRate')),
            ],
            options={
                'db_table': 'lastFriData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lastmondata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bay_id', models.IntegerField()),
                ('occupiedrate', models.FloatField(db_column='occupiedRate')),
            ],
            options={
                'db_table': 'lastMonData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lastsatdata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bay_id', models.IntegerField()),
                ('occupiedrate', models.FloatField(db_column='occupiedRate')),
            ],
            options={
                'db_table': 'lastSatData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lastsundata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bay_id', models.IntegerField()),
                ('occupiedrate', models.FloatField(db_column='occupiedRate')),
            ],
            options={
                'db_table': 'lastSunData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lastthudata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bay_id', models.IntegerField()),
                ('occupiedrate', models.FloatField(db_column='occupiedRate')),
            ],
            options={
                'db_table': 'lastThuData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lasttuedata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bay_id', models.IntegerField()),
                ('occupiedrate', models.FloatField(db_column='occupiedRate')),
            ],
            options={
                'db_table': 'lastTueData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lastweddata',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bay_id', models.IntegerField()),
                ('occupiedrate', models.FloatField(db_column='occupiedRate')),
            ],
            options={
                'db_table': 'lastWedData',
                'managed': False,
            },
        ),
    ]
